### ISSUE TITLE
Console Reporter

### ISSUE THREAD

**Issue by Sherlouk** [IBDecodable/IBLinter#10]
Similar to #8, another reporter type would be a simple console output! With this I'd love to see support for ANSI colors (with the option to turn them off using `--no-ansi` for console's that don't support it!) and maybe using emojis to indicate errors/warnings

Would also be sweet with this reporter in particular, if we could get a more "live" output where it tells you what file it's linting as it goes through (very much like SwiftLint)

⚠️ ❌

**Comment by phimage** [comment]
In development as EmojiReporter

**Comment by SD10** [comment]
Yes sorry @phimage 😓
