### ISSUE TITLE
High Sierra support

### ISSUE THREAD

**Issue by mgrebenets** [IBDecodable/IBLinter#103]
Hi there.

It appears that SwiftLint is build using Swift 5, which requires Xcode 10.2 and above as well as Mac OS X Mojave and above.

Not everyone can move that fast :) and our CI is still on High Sierra (unfortunately).
It's unfortunate that we can't use IBLinter on High Sierra.

How much of the code is Swift 5 specific?
Would it be a huge effort to make the tool compile with Swift 4.2 (Xcode 10.1)?

P.S.
Huge thanks for useful tool

**Comment by kateinoigakukun** [comment]
@mgrebenets Sorry for the inconvenience.  It seems same issue as https://github.com/IBDecodable/IBLinter/issues/93#issuecomment-482170933 🤔 
Please try to install `Swift 5 Runtime Support for Command Line Tools` from https://developer.apple.com/download/more/

I'll note this on README.md

**Comment by mgrebenets** [comment]
Thank you.
Confirmed that after installing Swift 5 runtime I can run `iblinter` downloaded from Releases page 👍 

I can't install it with Homebrew though, but that's not a big deal.
HOmebrew tries to build from source on High Sierra, but maybe it should install same portable version from a bottle instead? And maybe even install Swift 5 runtime or display a post-install message saying that runtime needs to be installed.

Thanks for helping out.
