### ISSUE TITLE
Resource Not Found

### ISSUE THREAD

**Issue by Sherlouk** [IBDecodable/IBLinter#11]
Xibs have an array called `resources` which contains things like images, would be nice to get the asset folders and check if the resource can be found (throwing an error if it can't)

**Comment by kateinoigakukun** [comment]
I have never faced with `resources` error in xib. Was this error happened when you edit `xib` file in Interface builder without text editor?

**Comment by Sherlouk** [comment]
Sorry I clearly explained it poorly, what I mean is we create a new rule which checks that all the resources are available

It's currently possible for you to add a UIImageView into a xib, and set the image to something that doesn't exist. Xcode handles this by showing a placeholder 'X' image!

What I'm suggesting is we add a rule which detects all of these situations where a xib references an image that doesn't exist - and IBLinter raises an error!

**Comment by kateinoigakukun** [comment]
It looks so useful! 👍
