### ISSUE TITLE
Randomly fails when the same name classes exists in two modules

### ISSUE THREAD

**Issue by sidepelican** [IBDecodable/IBLinter#113]
### Example 
- ModuleA and ModuleB have some classes like below.

```
ModuleA
  - XXXView 
  - YYYView
ModuleB
  - XXXView
  - ZZZView
```

- `AwesomeView` using `XXXView` in ModuleA.

In this case, IBLinter fails randomly with this message.
`- [ ] aaa/bbb/ccc/AwesomeView.xib#L0: It does not match custom module rule in AwesomeView. Custom module of XXXView is ModuleB`

Maybe this is caused by ↓

https://github.com/IBDecodable/IBLinter/blob/0bcc377d427faa21b2ebcea5d83acefecefc521c/Sources/IBLinterKit/Rules/CustomModuleRule.swift#L87

it selects target module with `first` in `Dictionary`

**Comment by kateinoigakukun** [comment]
@sidepelican Could you try this branch? https://github.com/IBDecodable/IBLinter/pull/114

**Comment by sidepelican** [comment]
@kateinoigakukun 
Thank you the fast implementation.

I tried in my project and it wasn't fine.
But I cannot analyze because of confused error message ( https://github.com/IBDecodable/IBLinter/pull/114#discussion_r326033539 ).   Please fix it first ?

**Comment by sidepelican** [comment]
https://github.com/IBDecodable/IBLinter/pull/114#issuecomment-533154652
