### ISSUE TITLE
IBLinter 0.4.18 cannot be installed via CocoaPods for ios platform

### ISSUE THREAD

**Issue by shosokawa** [IBDecodable/IBLinter#119]
We have updated `IBLinter` to `0.4.18` on `Podfile`, then we got this error at when it runs `pod install`. 
```[!] The platform of the target `Pods` (iOS 11.0) is not compatible with `IBLinter (0.4.18)`, which does not support `ios`.```

We have set up our project as it runs `IBLinter` installed via `CocoaPods` with [the reference](https://github.com/IBDecodable/IBLinter#xcode). 

I think that [this commit](https://github.com/IBDecodable/IBLinter/commit/7bc284aa6472a828f02726726e79952ec48f7830) is related to this.

**Comment by kateinoigakukun** [comment]
Sorry for confusion, I'll release hotfix version.
But 0.4.18 only contains a minor bug fix, so you may be able to use 0.4.17,

**Comment by shosokawa** [comment]
Thank you for your quick response!
We will use `0.4.17`.
