### ISSUE TITLE
How about reuseIdentifier rule?

### ISSUE THREAD

**Issue by r-plus** [IBDecodable/IBLinter#136]
Hi

How about new rule to check UITableViewCell, UICollectionReusableView, MKAnnotationView and UITableViewHeaderFooterView reuseIdentifier same as class name similar to `storyboard_viewcontroller_id`?

**Comment by kateinoigakukun** [comment]
Thanks. It seems very useful!

**Comment by r-plus** [comment]
Thanks! I’ll continue work to add this rule except MKAnnotationView and UITableViewHeaderFooterView that looks like IBDecodable not yet supported as concrete type.
