### ISSUE TITLE
Run Script

### ISSUE THREAD

**Issue by mfernandez94** [IBDecodable/IBLinter#145]
What would be the correct runscript phase if installed via pods after forking this repo? Forking seems to remove the unix executable "iblinter" and throwing a path no found

**Comment by kateinoigakukun** [comment]
As README.md says, you can run iblinter via `"${PODS_ROOT}/IBLinter/bin/iblinter"`

https://github.com/IBDecodable/IBLinter#xcode

**Comment by mfernandez94** [comment]
Yes, but I’m having an issue of when I fork the repo "${PODS_ROOT}/IBLinter/bin/iblinter" is no longer there, and get a run script error the it can’t be found

**Comment by kateinoigakukun** [comment]
I guess you didn't release your changed version of IBLinter to install via CocoaPods. The iblinter binary is  prebuilt on CI and uploaded to GitHub release page.
