### ISSUE TITLE
CocoaPods problem

### ISSUE THREAD

**Issue by emelyanovkirill** [IBDecodable/IBLinter#150]
If IBLinter was installed as pod, an empty line is displayed instead of warnings and errors.
If IBLinter was installed as brew, it shows warnings and errors.

**Comment by emelyanovkirill** [comment]
I use Swift 5

**Comment by kateinoigakukun** [comment]
@emelyanovkirill Thanks for your report!
What's your IBLinter version? and is there any error message from IBLinter?

**Comment by emelyanovkirill** [comment]
pod linter version: 0.4.21
brew linter version: 0.4.22

No, build script successful for both linter.

**Comment by kateinoigakukun** [comment]
OK, could you try to remove cache data in `~/Library/Caches/iblinter/` ?

**Comment by emelyanovkirill** [comment]
Thanks
