### ISSUE TITLE
Respect `verifyAmbiguity` Storyboard setting.

### ISSUE THREAD

**Issue by topLayoutGuide** [IBDecodable/IBLinter#153]
If you configure a `UIScrollView` on a XIB or Storyboard file to not verify its ambiguity, IBLinter will still trigger errors saying that the Auto Layout constraints are invalid.

You can find this setting in the Storyboard XML `<scrollView verifyAmbiguity="off" ...>`

This would be useful for when you configure the scroll view contents at runtime, and set up the constraints correctly based on dynamic content.

Does this make sense for this tool?

**Comment by kateinoigakukun** [comment]
Thanks! I didn't know that setting. I'll support that 👍
