### ISSUE TITLE
Default installation of IBLinter

### ISSUE THREAD

**Issue by piobyz** [IBDecodable/IBLinter#27]
Hi!
I like the idea behind IBLinter very much (the same as SwiftLint) and I'd like to contribute to it.

1. I think it lacks ability to check which rules are enabled by default (programmatically or at least in a form of documentation, the same as in SwiftLint). Maybe a good default would be to include all rules, right now there are not a lot of them.
2. Also, I'd like to be able to set a particular rule as a warning / error in .iblinter.yml
3. And it would be helpful to filter Xcode's issues list to contain IBLinter issues only, e.g. by containing a common issue prefix like "IBLinter: ...". I have a few "Shell Script Invocation Warning" besides IBLinter and thus I cannot differentiate between them.
4. Why is source code not contained within Xcode project?

Thanks!

**Comment by Sherlouk** [comment]
I can answer point four for you, this is a pattern with Swift Package Manager - As you'll see with the gitignore they supply (https://github.com/apple/swift-package-manager/blob/master/.gitignore) and the one within the repo the xcodeproj is ignored (I'm not too sure on the exact reason for this though)

You can generate one for yourself using `swift package generate-xcodeproj`

**Comment by kateinoigakukun** [comment]
@piobyz 

1. I agree that opinion to create documentation of rule. But it needs maintenance tools like https://github.com/danger/danger at least, and I have little time to install such tools 😢. For default rule, I think some of rules should not be included. (ex. RelativeToMarginRule) Default rules should be known as common in iOS developers, and rules which depend on local community should not be included.
2. Could you could make PR?
3. I'll add custom prefix config to `.iblinter.yml` 👍.
