### ISSUE TITLE
Make decoding less specific

### ISSUE THREAD

**Issue by SD10** [IBDecodable/IBLinter#31]
I noticed that on some models we explicitly decode things like `textColor` for `Label` or `titleColor` for `Button`. 

I think we should take a simpler approach and just store these things in an array of `Color` objects.

Then we can provide a computed property for a user to access a color with a given key like this:
```Swift

struct Button {
    // ...
    let colors: [Color]?

    var titleColor: Color? {
       return colors.first(where: { $0.key == "titleColor"} )
    }

    let states: [State]?

    var selected: State? {
        return states.first(where: {$0.key == "selected" })
    }
}
```

This is because it will be really difficult to decode all different key types because we don't know what kind of keys can exist. This approach assumes nothing.

Does this make sense?

**Comment by SD10** [comment]
I'm fine with this. You know a lot more about Storyboard XML than I do. My only concern was:

> I think no other attributed string will be added and this give more sense.

If it is not an array then we will miss some things if they do exist or if the XML changes in the future. Still, if you are sure there will only ever be 1 string, I think we can leave it.

**Comment by phimage** [comment]
This issue was moved to IBDecodable/IBDecodable#26
