### ISSUE TITLE
Make all properties of IBLinterCore models optional

### ISSUE THREAD

**Issue by SD10** [IBDecodable/IBLinter#33]
Currently, if a non-optional value does not exist the XML decoding fails. 

I think this is a drawback because it doesn't allow you to investigate the structural integrity of the XML. For example, you can't ever write rules that determine if a required key is missing. Maybe someone corrupted the XML through a merge conflict.

This is also a concern for `Boolean` properties. If the value doesn't exist, we don't want to assume it's false 🤔

**Comment by phimage** [comment]
For boolean properties I make some dirty code to have `true`as default value

```swift
clearsSelectionOnViewWillAppear: (try? xml.attributeValue(of: "clearsSelectionOnViewWillAppear")) ?? true
```

I think this issue could be moved to IBDecodable if we achieve this #38

**Comment by SD10** [comment]
Yeah @phimage I wanted your advice on this one. I think making everything optional is the way to go. Let me know what you think.

**Comment by phimage** [comment]
This issue was moved to IBDecodable/IBDecodable#25
