### ISSUE TITLE
Replace IBLinterCore with IBDecodable

### ISSUE THREAD

**Issue by SD10** [IBDecodable/IBLinter#38]
The goal is to replace IBLinterCore with [IBDecodable](https://github.com/IBDecodable/IBDecodable). Going to have the free time to tackle this one soon 💪

**Comment by phimage** [comment]
I will do it
I have already make locally the change

Just waiting on other PR merging to not create conflict

**Comment by SD10** [comment]
@phimage Do you need me to do this? I was planning on working on IBLinter this weekend
