### ISSUE TITLE
There is warning when installed by pods

### ISSUE THREAD

**Issue by bonyadmitr** [IBDecodable/IBLinter#48]
There is warning when installed by pods:
warning: no rule to process file '/Users/.../XcodeProjects/ScriptsTest/Pods/IBLinter/bin/iblinter' of type compiled.mach-o.executable for architecture x86_64

Also I see that IBLinter hierarchy is not as swiftlint or swiftgen.
Maybe that's why there is that warning.
![image](https://user-images.githubusercontent.com/24361363/40105527-df401a3c-58fb-11e8-8194-68e48284b49f.png)

**Comment by bonyadmitr** [comment]
podspec files examples

IBLinter
https://github.com/IBDecodable/IBLinter/blob/master/IBLinter.podspec
  s.source         = { :git => "https://github.com/IBDecodable/IBLinter.git", :tag => s.version }
  s.preserve_paths = 'bin/*'

SwiftGen
https://github.com/SwiftGen/SwiftGen/blob/master/SwiftGen.podspec
  s.source = { http: "https://github.com/SwiftGen/SwiftGen/releases/download/#{s.version}/swiftgen-#{s.version}.zip" }
  s.preserve_paths = '*'
  s.exclude_files = '**/file.zip'

SwiftLint
https://github.com/realm/SwiftLint/blob/master/SwiftLint.podspec
  s.source         = { :http => "#{s.homepage}/releases/download/#{s.version}/portable_swiftlint.zip" }
  s.preserve_paths = '*'
  s.exclude_files  = '**/file.zip'

IBAnalyzer
https://github.com/fastred/IBAnalyzer/blob/master/IBAnalyzer.podspec
  s.source       = { :http => "https://github.com/fastred/IBAnalyzer/releases/download/#{s.version}/ibanalyzer-#{s.version}.zip" }
  s.preserve_paths = '*'

**Comment by Dahlgren** [comment]
Fixed with #28

**Comment by bonyadmitr** [comment]
@Dahlgren 
But it is not fixed in current pod version

> Podile:
> pod 'IBLinter'
> Using IBLinter (0.2.0)

![image](https://user-images.githubusercontent.com/24361363/40121736-f1d71392-592a-11e8-9b90-cf794fd70224.png)

**Comment by Dahlgren** [comment]
Correct, there hasn’t been a new release yet

**Comment by bonyadmitr** [comment]
@Dahlgren 
Oh. When do you plan to do it?

**Comment by Dahlgren** [comment]
No idea, I'm just a contributor :)

**Comment by bonyadmitr** [comment]
@Dahlgren 
Sorry, didn't check it. Thank you!

Ok. I will leave it open until pod update.

**Comment by phimage** [comment]
@bonyadmitr no release for a little fix. will be one for new rules I think.
But you can with Cocoapod have the head master code by adding in Podfile the git and the branch for instance, or a specific commit hash
