### ISSUE TITLE
Add linting about`ambiguous`

### ISSUE THREAD

**Issue by tarunon** [IBDecodable/IBLinter#56]
Thanks nice software! We hope to use it in our proj.
Sometimes we told this things while code reviewing,
"Hey guys, there are `ambiguous = YES` here, is it ok?"
"Not ok, thanks"

I think that is awesome if we can find it while compile time. 👍

**Comment by kateinoigakukun** [comment]
Implemented in https://github.com/IBDecodable/IBLinter/pull/57  🎉
