### ISSUE TITLE
unable to run from Xcode 10

### ISSUE THREAD

**Issue by Speakus** [IBDecodable/IBLinter#76]
when I try to run `Pods/IBLinter/bin/iblinter` I got error:

module compiled with Swift 4.1.2 cannot be imported by the Swift 4.2 compiler: IBLinter.swiftmodule

**Comment by kateinoigakukun** [comment]
Related this issue. :bow: https://github.com/IBDecodable/IBLinter/issues/55#issuecomment-424709084
