### ISSUE TITLE
No such file or directory with 0.4.9

### ISSUE THREAD

**Issue by acevif** [IBDecodable/IBLinter#77]
Hello, 

After I upgraded from 0.4.4 to 0.4.9, errors like below occured:
> $ Pods/IBLinter/bin/iblinter lint
> Error parsing file system item: Error Domain=NSCocoaErrorDomain Code=260 "The file “***the-git-rebository-name***” couldn’t be opened because there is no such file." UserInfo={NSFilePath=file://***path-to-my-repository***//, NSUnderlyingError=0x7fd6d0613110 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
***path-to-my-repository***/***path-to-xib-file***::: error: ic_avatar not found
***path-to-my-repository***/***path-to-storyboard-file***::: error: bg_home not found
(snip)

How can I fix it?

Thank you in advance.

---
P.S.

In 0.4.8, no errors occurred.

Thanks.

**Comment by kateinoigakukun** [comment]
Sorry, I forgot to release a version that fixes this bug. 😥
I'm preparing to publish next version. Please wait a few moments.

**Comment by kateinoigakukun** [comment]
@acevif Could you try again with new version https://github.com/IBDecodable/IBLinter/releases/tag/0.4.10

**Comment by acevif** [comment]
家庭の医学 @kateinoigakukun さま

Thanks for the extremely quick update!
It works fine now! 

Thank you!

🙇
