### ISSUE TITLE
JSON Reporter

### ISSUE THREAD

**Issue by Sherlouk** [IBDecodable/IBLinter#8]
Currently it seems the only reporter pattern is internal to Xcode, it would be super helpful for third party services if we could have a JSON reporter swappable by passing a `reporter` parameter to the command?

This could follow a similar pattern to SwiftLint, where we would get access to the severity, file, and reason!

**Comment by kateinoigakukun** [comment]
That's exactly what I was thinking.
I'll implement this feature. 🙆

**Comment by phimage** [comment]
@kateinoigakukun I see you are working on it
I start too at the same time ;'(
