### ISSUE TITLE
add reporting in XML checkstyle format

### ISSUE THREAD

**Issue by nysander** [IBDecodable/IBLinter#90]
as this project is inspired by Swiftlint - it could be easily integrated into Jenkins CI with Warnings NG Plugin when using checkstyle XML report export.

Is it possible to add this to IBLinter?

**Comment by kateinoigakukun** [comment]
Yes, it's possible!
 I don't know `warning ng plugin` well. So if you have a time, would you implement CheckstyleReporter in IBLinterKit? 
It just to implement like [JSONReporter.swift](https://github.com/IBDecodable/IBLinter/blob/master/Sources/IBLinterKit/Reporters/JSONReporter.swift) and add swich case in https://github.com/IBDecodable/IBLinter/blob/master/Sources/IBLinterKit/Reporters/Reporter.swift#L16-L26

Please ask me anything!

**Comment by nysander** [comment]
I'm a bit newbe in swift world so I am not sure if I manage to do it. I will look at swiftlint sources if this can be aplied some way here

**Comment by nysander** [comment]
Merged

**Comment by nysander** [comment]
@kateinoigakukun just little report. 2 days ago new version of Jenkins' Warnings NG plugin was released and today I've made first test ... result below :)

Happy to have your linter in my setup

![image](https://user-images.githubusercontent.com/753327/57486045-82bf6200-72ad-11e9-8a70-d7beecc111e7.png)
